name: fluttersocial
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cloud_firestore: ^0.14.4
  image_picker: ^0.6.7+17
  firebase_storage: ^5.2.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_analytics: ^6.3.0
  google_sign_in: ^4.5.6
  geolocator: ^6.1.13
  uuid: ^2.2.2
  image: ^2.1.19
  animator: ^2.0.2
  path_provider: ^1.6.24
  timeago: ^2.0.29
  cached_network_image: ^2.5.0
  flutter_svg: ^0.19.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
